FROM node:16-alpine AS builder
# ENV NODE_ENV production
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
# COPY package-lock.json .
RUN npm install
# Copy app files
COPY . .
# Run unit test
# ENV CI=true
# RUN npm run test:coverage
# Build the app
RUN npm run build


