#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS final
EXPOSE 80
EXPOSE 443

WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "Inventoryservice.Api.dll"]